spring:
  datasource:
    driver-class-name: org.h2.Driver
    username: sa
    password: 123456
    url: jdbc:h2:./data/hertzbeat;MODE=MYSQL
    hikari:
      max-lifetime: 120000
  h2:
    console:
      path: /h2-console
      enabled: true
  jpa:
    show-sql: false
    database-platform: org.eclipse.persistence.platform.database.MySQLPlatform
    database: h2
    properties:
      eclipselink:
        logging:
          level: SEVERE
  flyway:
    enabled: true
    clean-disabled: true
    baseline-on-migrate: true
    baseline-version: 1
    locations:
      - classpath:db/migration/{vendor}
      
  mail:
    host: smtp.exmail.qq.com
    username: sss@tancloud.cn
    password: sss
    port: 465
    default-encoding: UTF-8
    properties:
      mail:
        smtp:
          socketFactoryClass: javax.net.ssl.SSLSocketFactory
          ssl:
            enable: true

management:
  health:
    mail:
      enabled: off
  endpoints:
    web:
      exposure:
        include:
          - 'metrics'
          - 'health'
    enabled-by-default: on

sureness:
  auths:
    - digest
    - basic
    - jwt

warehouse:
  store:
    jpa:
      enabled: false
      expire-time: 1h
    victoria-metrics:
      enabled: false
#      url: http://82.157.76.80:8428
      url: http://localhost:8428
      username: root
      password: root
    influxdb:
      enabled: false
      #      server-url: https://121.37.174.225:8635
      #      username: rwuser
      #      password: Dromara@123
      server-url: http://localhost:8086
      username: root
      password: root
    td-engine:
      enabled: false
      driver-class-name: com.taosdata.jdbc.rs.RestfulDriver
      url: jdbc:TAOS-RS://localhost:6041/hertzbeat
      username: root
      password: taosdata
    iot-db:
      enabled: false
      host: 127.0.0.1
      rpc-port: 6667
      username: root
      password: root
      # org.dromara.hertzbeat.warehouse.config.IotDbVersion: V_0_13 || V_1_0
      version: V_1_0
      query-timeout-in-ms: -1
      # 数据存储时间：默认'7776000000'（90天,单位为毫秒,-1代表永不过期）
      # data expire time, unit:ms, default '7776000000'(90 days, -1:never expire)
      expire-time: '7776000000'
    redis:
      enabled: false
      host: 127.0.0.1
      port: 6379
      password: 123456
    memory:
      enabled: true
      init-size: 16

common:
  sms:
    #        tencent:
    #          secret-id: AKIDbQ4VhdMr89wUmotjIcgU2PaaMvOuBCzY
    #          secret-key: PaXGl0ziY9UcWFjyyiCPMr77rLkJYlyA
    #          app-id: 1400781637
    #          sign-name: 探云科技
    #          template-id: 1636532
    org-single:
      url: http://172.16.18.22
      app-id: dcms
      app-secret: 1bdb0b1b9d10bb1228dbd371a2db53e5
      company: 194370
  queue:
    # memory or kafka
    type: memory
    # properties when queue type is kafka
    kafka:
      servers: 139.198.109.64:9092
      metrics-data-topic: async-metrics-data
      alerts-data-topic: async-alerts-data

scheduler:
  server:
    enabled: true
    port: 1159
